baseURL = 'http://jakubowemysli.pl/'
title = 'Myśli Jakubowe'
theme = "shibui"

[params]
  author = "Jakub Strauchmann"
  email = "jakubstrauchmann@gmail.com"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Galeria"
    url = "/galeria/"
    weight = 2
  [[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 3    

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      attr = true

[taxonomies]
  tag = "tags"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
