# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.5"

[functions.environment]
NODE_OPTIONS = "--openssl-legacy-provider"
